setup auto redirect to https://moodledemo.pascal.id
Bephometh/moodleapp pull request #7
Opened 2020-12-22 04:19 UTC by Bephometh

2020-12-22 04:48 UTC, pascalalfadian requested changes

2020-12-22 04:48 UTC, pascalalfadian commented on config.xml
> +<widget android-versionCode="10000" id="com.ide.mobile" ios-CFBundleVersion="1.0.0.0" version="1.0.0" versionCode="10000" xmlns="http://www.w3.org/ns/widgets" xmlns:android="http://schemas.android.co
id nya gunakan `id.ac.unpar.moodlemobile`, disesuaikan dengan domain UNPAR.

2020-12-22 04:48 UTC, pascalalfadian commented on config.xml
> +    <author email="gabriel.lazuardi@gmail.com" >Gabriel Panji Lazuardi</author>
Gunakan e-mail student

2020-12-22 04:48 UTC, pascalalfadian commented on src/config.json
> +    "app_id": "com.ide.mobile",
Ini juga, disesuaikan

2020-12-22 04:48 UTC, pascalalfadian commented on src/config.json
> +    "presets" : {"url" :"https://moodledemo.pascal.id/"},
Catat URL forum yang memberitahu kamu bagaimana cara mengubah ini. Nanti di dokumen skripsi mesti ada juga.

2021-01-13 12:03 UTC, Bephometh commented
Link to forums that discussed the auto redirect setup : https://moodle.org/mod/forum/discuss.php?d=280042

2021-03-15 04:51 UTC, Bephometh commented
Apparently, to deploy on mobile you need to change the app id in `google-service.json` since the default app id was chaged and conflicted with the app id in `google-service.json` this was not mentioned in their documentation

2021-03-16 07:32 UTC, merged